# Generated by Django 5.2.5 on 2026-03-31 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_must_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='If True the user must set a new password on next login'),
        ),
    ]
