# Generated by Django 4.2.29 on 2026-04-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventorylog_change_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorylog',
            name='change_type',
            field=models.CharField(choices=[('add', 'Add Stock'), ('remove', 'Remove Stock'), ('sale', 'Sale'), ('adjust', 'Adjustment')], max_length=10),
        ),
    ]
