# Generated by Django 5.2.5 on 2026-03-18 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='cash_received',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='change_given',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
