# Generated by Django 4.2.29 on 2026-04-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_cash_received_sale_change_given'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('other', 'Other')], default='cash', max_length=10),
        ),
    ]
